

execution:
  celery:    
    broker: 'pyamqp://guest:guest@rabbitmq:5672//'  # Optional[str]: The URL of the Celery broker
    backend: 'rpc://guest:guest@rabbitmq:5672//' # Optional[str]: The URL of the Celery results backend
  #   include: ['my_module'] # Optional[List[str]]: Modules every worker should import
  config_source:
    broker_transport_options:
      visibility_timeout: 18000
