version: '3'

services:

  dagster_postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      # POSTGRES_HOST: dagster_postgres
      POSTGRES_DB: dagster

  dagster_instance:
    image: dagster_instance
    expose:
      - 3000
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - dagster_postgres
    environment:
      DAGSTER_PG_USERNAME: dagster
      DAGSTER_PG_PASSWORD: dagster
      DAGSTER_PG_HOST: dagster_postgres
      DAGSTER_PG_DB: dagster
    volumes: 
      - './dagster_home:/opt/dagster/dagster_home'
      - './app:/opt/dagster/app'


  #   healthcheck:
  #     test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

#   Dagit servers expose a health check endpoint at /dagit_info, which returns a JSON response like:

# {
#   "dagit_version": "0.6.6",
#   "dagster_graphql_version": "0.6.6",
#   "dagster_version": "0.6.6"
# }