version: '3.1'

services:

  mlflowdb:
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - './mlflowdb:/var/lib/postgresql/data/pgdata'

  mlflow:
    image: mlflow
    expose:
      - 5000
    ports:
      - "5000:5000"
    restart: always
    environment:
      MLFLOWDB: postgresql://postgres:postgres@mlflowdb:5432/mlflowdb